apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app-blue
  labels:
    app: django-messaging-app
    version: blue
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: django-messaging-app
      version: blue
  template:
    metadata:
      labels:
        app: django-messaging-app
        version: blue
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:v2.0
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DB
          value: "messaging_app"
        - name: MYSQL_USER
          value: "messaging_user"
        - name: MYSQL_PASSWORD
          value: "#Nasimiyu1"
        - name: MYSQL_ROOT_PASSWORD
          value: "#Nasimiyu1"
        - name: MYSQL_HOST
          value: "localhost"
        - name: MYSQL_PORT
          value: "3306"
        - name: DJANGO_SECRET_KEY
          value: "django-insecure-+g1^=&c^c%$c1p%pa!yj&u4)k-6nfdwb!my8kxheia-2(1)fgx"
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1"
        - name: VERSION
          value: "blue-v2.0"
        - name: UPDATE_TYPE
          value: "rolling-update"
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5