pipeline{
    agent{
        docker{
            image 'python: 3.10'
        }
    }
    environment {
        VENV = 'venv'
    }
    stages {
        stage('Checkout') {
            steps {
                git(
                    url: 'https://github.com/Darlene-13/alx-backend-python.git'
                    branch: 'main',
                    credentialsId: 'github-credentials'
                )
            }
        }
        stage('Install Dependencies'){
            steps {
                sh '''
                    python -m venv $VENV
                    . $VENV/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }
        stage('Run Tests') {
            steps{
                sh '''
                    . $VENV/bin/activate
                    pytest messaging_app/testa --junitxml=report.xml
                '''
            }
        }
        stage('Publish Test Report'){
            steps{
                junit 'report.xml'
            }
        }
    }
}