apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-messaging-app
  labels:
    app: django-messaging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-messaging-app
  template:
    metadata:
      labels:
        app: django-messaging-app
    spec:
      containers:
      - name: messaging-app
        image: messaging-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DB
          value: "messaging_app"
        - name: MYSQL_USER
          value: "messaging_user"
        - name: MYSQL_PASSWORD
          value: "#Nasimiyu1"
        - name: MYSQL_ROOT_PASSWORD
          value: "#Nasimiyu1"
        - name: MYSQL_HOST
          value: "localhost"
        - name: MYSQL_PORT
          value: "3306"
        - name: DJANGO_SECRET_KEY
          value: "django-insecure-+g1^=&c^c%$c1p%pa!yj&u4)k-6nfdwb!my8kxheia-2(1)fgx"
        - name: DEBUG
          value: "True"
        - name: ALLOWED_HOSTS
          value: "localhost,127.0.0.1"
        imagePullPolicy: Never
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: django-messaging-service
  labels:
    app: django-messaging-app
spec:
  selector:
    app: django-messaging-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP